[[redirects]]
  from = "/photos-for-hack.html"
  to = "/photos-for-hack"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/main"
  status = 200

[[redirects]]
  from = "/login/login"
  to = "/login"
  status = 200
